language: node_js
node_js:
- node
install:
- npm install -g eslint
- npm install -g mocha
- npm install -g mocha-eslint
- npm install
deploy:
  provider: npm
  email: jdrickerd@gmail.com  
  api_key:
    secure: F9NMxhTf+X6fzpnQgkZpBBk2bqZisQYD0tjmLqHzVKWZIbT86eBmRn4NKl5mXrxiufLhRZL8F+sXbwP9gCqYb3jdF4SvsE3qedn+8pEBsuPxyipVR5ILJeHzG3HzTEYONISHIFIHMp5cyokF86DxrTMHm+HWJK4qdZMeF28p1E4LAM8vKYa0YhdSJOuRNfRrK/FFOpiJo6S5Ms0Ht6q/lSnTtowaZDI9OH5OGGe0tVxbgMYi4JUelnYwoNkQwEsBOLqAMKESvD4kTWEoDYE4OfgAU6wgS4H6vWwVIxqSypdgnvLzbxYlH6RrMlxIl8BvNUrDauRmvDM6YyDHM69OxK+rBlYvIjUOxc4HK99nNu2ER3U4VtIOVit/X0gqMGrjwBIFxKW8BI/D+ryR7txwfkDa4UMlnQHASr0Ul+E8IwwiRCf6sjt+pZ/CDBu7fdPT2qsFf8hweXzQZbU7YJ94AXL666LSm4oxUN6tOWp8vmjL+4F+Lt5w300yAOVDiRyB1IvVLLaWL2g/7q408xv42sia2DE7kRQVcu7qJAaEuNNbxPvQfKPDm2zqzfeHDdo9roRlLcKozqNem8ECYBMdXTdjcRlrvXlB3XspTEtkhIYUJxCymNYvIWpHJ0TwKDeR66f17FYOJEXVMt2yHDRAI2wACOvpFMEYlMZH6vw+i7E=
  on:
    tags: true